name: macos-armv8

on: push

jobs:
  linux:
    name: macos-armv8
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos armv8 compilation
        run: |
          ./install.sh --target=ios-aarch64 -t 32
