name: windows-x86-avx2
on: push
defaults:
  run:
    shell: bash
jobs:
  windows-vs2019:
    name: windows-x86-avx2
    runs-on: windows-latest
    steps:  
      - name: checkout code
        uses: actions/checkout@v2
      - name: windows x86 avx2 compilation
        run: |
          Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/archive/v3.11.2.zip -OutFile protobuf-3.11.2.zip
          cmake -version
          mingw32-make -version
          echo "***enter the shell environment"
          ls
          echo "***list all the files"
